---
- name: Install Apache
  apt:
          name: apache2
          update_cache: yes

- name: Expose public toolchain directory
  file:
          src: /var/results/toolchains
          dest: /var/www/html/toolchains
          state: link

- name: Expose public config directory
  file:
          src: /var/results/conffiles
          dest: /var/www/html/conffiles
          state: link
